### ISSUE TITLE
Output local customizations as ansible

### ISSUE THREAD

**Issue by marusak** [SELinuxProject/selinux#197]
`semanage export` lists all local modifications that can be used in shell script.
It would be super useful to generate this as ansible task.

Something like `semanage export --ansible` and the output could look something like:
```
- name: Allow virt to sandbox use all caps
  seboolean:
    name: virt_sandbox_use_all_caps
    state: yes
    persistent: yes

- name: Allow virt to use nfs
  seboolean:
    name: virt_use_nfs
    state: yes
    persistent: yes
```

I would be interested in helping to implement this. Firstly asking if this is something that would get accepted.
